name: dummy
on: [push]

jobs:
  dummy_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: dummy action step
        id: dum
        uses: MaliMi97/dummy-action@v1
        with:
          who-to-greet: 'Dummy!'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"